# Generated by Django 4.2.30 on 2026-06-11, hand-tuned to migrate existing rows:
# legacy users have phone="" (and possibly email=""), which would collide once
# the columns become unique. We loosen the columns first, convert blanks to
# NULL, then apply the unique constraints.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def blanks_to_null(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(phone="").update(phone=None)
    User.objects.filter(email="").update(email=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_consultantapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        # Step 1: make both columns nullable, WITHOUT uniqueness on phone yet.
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Step 2: normalize legacy empty strings to NULL.
        migrations.RunPython(blanks_to_null, migrations.RunPython.noop),
        # Step 3: now the unique constraints are safe to apply.
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email', 'Email verification'), ('otp', 'Phone OTP'), ('reset', 'Password reset'), ('reset_otp', 'Password reset OTP')], max_length=20)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
